ci(ios): fix indentation

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -36,11 +36,11 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Make sure that Package.swift is not configured for local development
-      run: |
-        if grep -q "let useLocalFramework = true" Package.swift; then
-          echo "Error: Package.swift is configured for local development. Please set useLocalFramework to false."
-          exit 1
-        fi
+        run: |
+          if grep -q "let useLocalFramework = true" Package.swift; then
+            echo "Error: Package.swift is configured for local development. Please set useLocalFramework to false."
+            exit 1
+          fi
 
       - name: Build iOS XCFramework
         run: ./build-ios.sh --release
